name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions: 
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          config-file: nuget.config
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: overwrite with correct credentials (this is not necessary if the PAT is already in the nuget.config)
        run: dotnet nuget update source myPrivateRepo --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --configfile nuget.config
      - name: Build with dotnet
        run: dotnet build -c Release
      - name: run
        run: dotnet run --project dummyApp  